#!/bin/bash

#1. Install with pip
pip3 install breidablik

#2,3. Optional, download the raw data and put it in the breidablik folder
while true; do
    read -p "Do you wish to download the raw data? [Y/n] " yn
    [ -z "${yn}" ] && yn='y'
    case $yn in
        [Yy]* ) LOC=$(pip3 show breidablik | grep "Location");
                INSTALL_PATH=${LOC:9}
                OLD_PWD=$(pwd)
                cd $INSTALL_PATH/breidablik;
                wget http://www.mso.anu.edu.au/~ellawang/balder.zip;
                unzip -q balder.zip;
                rm balder.zip;
                cd $OLD_PWD;
                break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

# remove the repo
cd ..
rm -rf Breidablik
