#!/bin/bash
#2. Navigate into the subdirectory
cd breidablik
#3. Download models
wget http://www.mso.anu.edu.au/~ellawang/models.zip
unzip models.zip
rm models.zip
#4. Download data
wget http://www.mso.anu.edu.au/~ellawang/balder.zip
unzip balder.zip
rm balder.zip
#5. Optional, add to python path
while true; do
    read -p "Do you wish to add this package to the python path? [Y/n]" yn
    [ -z "${yn}" ] && yn='y'
    case $yn in
        [Yy]* ) cd ..; path=$(pwd); echo -e "\n# Add breidablik to PYTHONPATH" >> ~/.bashrc; echo "export PYTHONPATH=$path:"'$PYTHONPATH' >> ~/.bashrc; source ~/.bashrc; break;;
        [Nn]* ) cd ..; exit;;
        * ) echo "Please answer yes or no.";;
    esac
