#!/bin/bash
#2. Navigate into the subdirectory
cd breidablik
#3. Download models
wget https://zenodo.org/records/13829605/files/models_v1.5.0.zip
unzip -q models_v1.5.0.zip
rm models_v1.5.0.zip
#4. Optional, download data
while true; do
    read -p "Do you wish to download the data from Balder? [Y/n] " yn
    [ -z "${yn}" ] && yn='y'
    case $yn in 
        [Yy]* ) wget https://zenodo.org/records/10450568/files/balder.zip;
            unzip -q balder.zip;
            rm balder.zip;
            break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
#5. Optional, add to python path
while true; do
    read -p "Do you wish to add this package to the python path? [Y/n] " yn
    [ -z "${yn}" ] && yn='y'
    case $yn in
        [Yy]* ) cd ..;
                path=$(pwd);
                echo -e "\n# Add breidablik to PYTHONPATH" >> ~/.bashrc;
                echo "export PYTHONPATH=$path:"'$PYTHONPATH' >> ~/.bashrc;
                source ~/.bashrc;
                break;;
        [Nn]* ) cd ..;
                exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
